name: rapid
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow>=23.04.0
  - r-base>=4.2.0
  - r-data.table
  - r-ggplot2
  - r-ggrepel
  - r-rmarkdown
  - r-knitr
  - r-kableextra
  - r-bit64
  - bioconductor-limma
  - bioconductor-deqms
  - bioconductor-clusterprofiler
  - bioconductor-enrichplot
  - bioconductor-org.hs.eg.db
  - wget